package org.cz.project.entity.table;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

// Generated 2015-7-5 23:00:03 by Hibernate Tools 3.4.0.CR1

/**
 * TownInfoId generated by hbm2java
 */
@Entity
@Table(name = "JhPanWeather.dbo.Probe_Oxy_PerHour")
@NamedQueries({ @NamedQuery(name = "findAllProbeOxyPerHour", query = "SELECT g FROM ProbeOxyPerHour g")})
public class ProbeOxyPerHour implements java.io.Serializable {
	@Id
	//@Column(name="Temp24H") 
	private Long ID;
	private Integer Date;
	private String Time;
	private String Areacode;
	private String Stationnum;
	private Integer O2;
	private Integer MaxO2;
	private Integer MinO2;
	private java.sql.Date Renewtime;

	public ProbeOxyPerHour() {
	}

	public Long getID() {
		return ID;
	}

	public void setID(Long iD) {
		ID = iD;
	}

	public Integer getDate() {
		return Date;
	}

	public void setDate(Integer date) {
		Date = date;
	}

	public String getTime() {
		return Time;
	}

	public void setTime(String time) {
		Time = time;
	}

	public String getAreacode() {
		return Areacode;
	}

	public void setAreacode(String areacode) {
		Areacode = areacode;
	}

	public String getStationnum() {
		return Stationnum;
	}

	public void setStationnum(String stationnum) {
		Stationnum = stationnum;
	}

	public Integer getO2() {
		return O2;
	}

	public void setO2(Integer o2) {
		O2 = o2;
	}

	public Integer getMaxO2() {
		return MaxO2;
	}

	public void setMaxO2(Integer maxO2) {
		MaxO2 = maxO2;
	}

	public Integer getMinO2() {
		return MinO2;
	}

	public void setMinO2(Integer minO2) {
		MinO2 = minO2;
	}

	public java.sql.Date getRenewtime() {
		return Renewtime;
	}

	public void setRenewtime(java.sql.Date renewtime) {
		Renewtime = renewtime;
	}

}
