package org.cz.project.entity.table;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

// Generated 2015-7-5 23:00:03 by Hibernate Tools 3.4.0.CR1

/**
 * TownInfoId generated by hbm2java
 */
@Entity
@Table(name = "JhPanWeather.dbo.town_info")
@NamedQueries({ @NamedQuery(name = "findAllTownInfo", query = "SELECT g FROM TownInfo g")})
public class TownInfo implements java.io.Serializable {
	@Id
	private Long id;
	private String stid;
	private Float stlon;
	private Float stlat;
	private Float stht;
	private String province;
	private String prefecture;
	private String county;
	private String countyid;
	private String town;
	private String stname;

	public TownInfo() {
	}

	public TownInfo(Long id, String stid, Float stlon, Float stlat,
			Float stht, String province, String prefecture, String county,
			String town) {
		this.id = id;
		this.stid = stid;
		this.stlon = stlon;
		this.stlat = stlat;
		this.stht = stht;
		this.province = province;
		this.prefecture = prefecture;
		this.county = county;
		this.town = town;
	}

	public TownInfo(Long id, String stid, Float stlon, Float stlat,
			Float stht, String province, String prefecture, String county,
			String countyid, String town, String stname) {
		this.id = id;
		this.stid = stid;
		this.stlon = stlon;
		this.stlat = stlat;
		this.stht = stht;
		this.province = province;
		this.prefecture = prefecture;
		this.county = county;
		this.countyid = countyid;
		this.town = town;
		this.stname = stname;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getStid() {
		return this.stid;
	}

	public void setStid(String stid) {
		this.stid = stid;
	}

	public Float getStlon() {
		return this.stlon;
	}

	public void setStlon(Float stlon) {
		this.stlon = stlon;
	}

	public Float getStlat() {
		return this.stlat;
	}

	public void setStlat(Float stlat) {
		this.stlat = stlat;
	}

	public Float getStht() {
		return this.stht;
	}

	public void setStht(Float stht) {
		this.stht = stht;
	}

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getPrefecture() {
		return this.prefecture;
	}

	public void setPrefecture(String prefecture) {
		this.prefecture = prefecture;
	}

	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	public String getCountyid() {
		return this.countyid;
	}

	public void setCountyid(String countyid) {
		this.countyid = countyid;
	}

	public String getTown() {
		return this.town;
	}

	public void setTown(String town) {
		this.town = town;
	}

	public String getStname() {
		return this.stname;
	}

	public void setStname(String stname) {
		this.stname = stname;
	}
}
